### ISSUE TITLE
The port number is hidden by the color same with background

### ISSUE THREAD

**Issue by JonasGao** [Zabanaa/neuromancer.vim#2]
i`m using ``chr4/nginx.vim`` too

and, i cant see the port number

![2017-08-21 12 45 50](https://user-images.githubusercontent.com/4549584/29504010-12783368-866f-11e7-8a3c-eb92eed50ea1.png)

because the number color same with background. :sweat:

![2017-08-21 12 45 25](https://user-images.githubusercontent.com/4549584/29503976-cad3f4c0-866e-11e7-98bc-6af2f5a6172b.png)

**Comment by Zabanaa** [comment]
Thanks Jonas for spotting the issue, It's fixed now :smile: 
Also, do you mind sharing what font you're using on your terminal ? 
Cheers

**Comment by Zabanaa** [comment]
Also, I have yet to make a start on nginx config files, so it will look a lot better once I push all the updates 
:smile: ! Be on the lookout !
